# Generated by Django 4.2.7 on 2024-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('google_access_token', models.CharField(default='', max_length=250)),
                ('shopify_access_token', models.CharField(default='', max_length=100)),
                ('shop', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
