# Generated by Django 4.2.7 on 2024-01-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnections',
            name='refresh_token',
            field=models.CharField(default='', max_length=250),
        ),
    ]
