# Generated by Django 4.2.7 on 2024-01-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0002_userconnections_refresh_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconnections',
            old_name='refresh_token',
            new_name='google_refresh_token',
        ),
    ]
