# Generated by Django 4.2.7 on 2024-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0003_rename_refresh_token_userconnections_google_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('spreadsheet_id', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='userconnections',
            old_name='google_access_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='userconnections',
            old_name='shopify_access_token',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='userconnections',
            old_name='google_refresh_token',
            new_name='refresh_token',
        ),
    ]
