# Generated by Django 4.2.7 on 2024-01-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0004_useraccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnections',
            name='platform',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('google', 'Google')], max_length=100),
        ),
    ]
