# Generated by Django 4.2.7 on 2024-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0005_alter_userconnections_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('published_at', models.DateField()),
            ],
        ),
    ]
