# Generated by Django 4.2.7 on 2024-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0006_shopifydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifydata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
