# Generated by Django 4.2.7 on 2024-01-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0007_shopifydata_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifydata',
            name='published_at',
        ),
    ]
