# Generated by Django 4.2.7 on 2024-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0008_remove_shopifydata_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='userconnections',
            name='spreadsheet_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
