# Generated by Django 4.2.7 on 2024-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0009_delete_useraccount_userconnections_spreadsheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifydata',
            name='row_range',
            field=models.CharField(default='', max_length=100),
        ),
    ]
