# Generated by Django 4.2.7 on 2024-01-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0010_shopifydata_row_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifydata',
            name='sync_flag',
            field=models.BooleanField(default=False),
        ),
    ]
